ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # https://nvd.nist.gov/vuln/detail/CVE-2024-10963
  # Severity: High (Medium from Ubuntu)
  # A vulnerability in pam_access where some rules are incorrectly interpreted as hostnames.  The image does not
  # leverage the pam_access config file
  # Original analysis: 2024-11-20
  # Last reviewed: 2025-07-29
  # Next review due: 2025-08-29
  - vulnerability: CVE-2024-10963

  # https://nvd.nist.gov/vuln/detail/CVE-2025-30749
  # https://nvd.nist.gov/vuln/detail/CVE-2025-50106
  # https://nvd.nist.gov/vuln/detail/CVE-2025-50059
  # https://nvd.nist.gov/vuln/detail/CVE-2025-30754
  # Bug: BUG-940984
  # Severity: High
  # These CVEs are fixed upstream but we are blocked waiting for https://github.com/adoptium/temurin/issues/89.
  # Once the fix is available we will immediately pull in the fix and rebuild.
  # No known exploit related to Pega servers but there is potentially a risk - currently waiting for updates.
  # Original analysis: 2025-07-28
  # Last reviewed: 2025-07-29
  # Next review due: 2025-08-29
  - vulnerability: CVE-2025-30749
  - vulnerability: CVE-2025-50106
  - vulnerability: CVE-2025-50059
  - vulnerability: CVE-2025-30754
