ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # Disputed scanner issue https://github.com/anchore/grype/issues/504
  - vulnerability: CVE-2002-0493
  - vulnerability: CVE-2013-2185
  - vulnerability: CVE-2016-5425
  - vulnerability: CVE-2016-6325
  - vulnerability: CVE-2020-8022
  - vulnerability: CVE-2022-42800
  - vulnerability: CVE-2024-34156
  - vulnerability: CVE-2024-34158

  # https://nvd.nist.gov/vuln/detail/CVE-2025-22874
  # Calling Verify with a VerifyOptions.KeyUsages that contains ExtKeyUsageAny unintentionally disabledpolicy validation.
  # This only affected certificate chains which contain policy graphs, which are rather uncommon.
  # The CVE is originating from the go standard library included in detemplatize utility and does not leverage the
  # particularly problematic go methods.
  # Severity: High
  # Date Detected: 2025-06-16
  # Date of next action: 2025-07-16
  - vulnerability: CVE-2025-22874
    fix-state: "not-fixed"

  # https://nvd.nist.gov/vuln/detail/CVE-2020-35527  https://ubuntu.com/security/CVE-2020-35527
  # In SQLite 3.31.1, there is an out of bounds access problem through ALTER TABLE for views that have a nested FROM clause.
  # SQLite is not leverage by this image. A fix appears to be in progress.
  - vulnerability: CVE-2020-35527
    fix-state: "not-fixed"

  # https://nvd.nist.gov/vuln/detail/CVE-2024-24791  https://ubuntu.com/security/CVE-2024-24791
  # net/http libraries from GoLang are not utilized in this image.
  - vulnerability: CVE-2024-24791

  # https://nvd.nist.gov/vuln/detail/CVE-2025-22871  https://ubuntu.com/security/CVE-2025-22871
  # Severity: Critical
  # net/http libraries from GoLang are not utilized in this image. As such image is not vulnerable.
  - vulnerability: CVE-2025-22871

  # https://nvd.nist.gov/vuln/detail/CVE-2025-21587
  # Severity: High
  # Valid vulnerability, difficult to exploit. Waiting for patch from Adoptium upstream. Image will be
  # updated automatically upon release.
  # Recommend waiting for upstream fix, as the fix will be provided in the near future.
  # Concerned clients should avoid loading untrusted code into the platform until this is resolved.
  # Unspecified network protocols are impacted - not enough information yet to determine risk.
  # This is less relevant for the platform installer - more relevant for a running Pega image.
  - vulnerability: CVE-2025-21587