ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # https://nvd.nist.gov/vuln/detail/CVE-2024-10963
  # Severity: High (Medium from Ubuntu)
  # A vulnerability in pam_access where some rules are incorrectly interpreted as hostnames.  The image does not
  # leverage the pam_access config file
  # Original analysis: 2024-11-20
  # Last reviewed: 2025-11-04
  # Next review due: 2025-08-29
  - vulnerability: CVE-2024-10963

  # https://nvd.nist.gov/vuln/detail/CVE-2025-53066
  # Severity: High
  # Awaiting fix from upstream - no known exploit related to Pega servers, but will continue to watch for any issues.
  # Original analysis: 2025-11-04
  # Last reviewed: 2025-11-04
  # Next review due: 2025-12-04
  - vulnerability: CVE-2025-53066
  
  # CVE-2025-58187 - https://github.com/advisories/GHSA-frhw-mqj2-wxw2
  # CVE-2025-58188 - https://github.com/advisories/GHSA-7wwx-xj66-r44x
  # CVE-2025-61723 - https://github.com/advisories/GHSA-hjx7-fpxx-mj48
  # CVE-2025-61725 - https://github.com/advisories/GHSA-qh38-484v-w52x
  # Severity: High
  # Due to the way we leverage go, we do not believe we are vulnerable to any of these, but the relevant project
  # should be updated in the near future regardless.
  # Original analysis: 2025-11-04
  # Last reviewed: 2025-11-04
  # Next review due: 2025-12-04
  - vulnerability: CVE-2025-58187
  - vulnerability: CVE-2025-58188
  - vulnerability: CVE-2025-61723
  - vulnerability: CVE-2025-61725
