services:
- docker

install:
  - make image
  - docker images
  
script:
  - docker images
  - docker ps
  - bash tests/setup.sh "$DOCKER_USER" "$REPO_NAME"


before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

deploy:
  provider: script
  script: make push

