
tags=jdk11,jdk17,jdk21

latestTag=jdk17
qualityCheckTag=jdk11

# registryUrl is optional, and should only be supplied if your docker registry requires authentication (set via
# dockerRegistryUser and dockerRegistryPassword Gradle props)

jdk11.baseImage=your_base_image_repo:tomcat9-jdk11
jdk11.jdk=jdk11
jdk11.tomcat=9
jdk11.registryUrl=

jdk17.baseImage=your_base_image_repo:tomcat9-jdk17
jdk17.jdk=jdk17
jdk17.tomcat=9
jdk17.registryUrl=

jdk21.baseImage=your_base_image_repo:tomcat10-jdk21
jdk21.jdk=jdk21
jdk21.tomcat=10
jdk21.registryUrl=

