name: Docker Image CI

env:
  IMAGE_NAME: pegasystems/pega-ready
  VERSION: 2.1.0-${GITHUB_REPOSITORY%%/*}-${GITHUB_SHA}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Container Tests
    runs-on: ubuntu-latest
    steps:
    - name: echo-default-env-variables
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"

    - name: Check out working repository
      uses: actions/checkout@v2

    - name: Run Container Tests
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
        make test
        
  scan:
    name: Scan for CVEs
    runs-on: ubuntu-latest
    steps:
    - name: Check out working repository
      uses: actions/checkout@v2
      
    - name: Build Image
      run: make image

    - name: Scan image
      id: scan
      uses: anchore/scan-action@v2
      with:
        image: "pegasystems/pega-ready:latest"
        fail-build: true
        severity-cutoff: "high"
        acs-report-enable: true
        
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
      
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
