name: Docker Image CI

env:
  IMAGE_NAME: pegasystems/pega-ready
  VERSION: 2.1.0-x

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo-default-env-variables
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"
    - name: Check out working repository
      uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image via makefile
      run: make image
#    - name: Build and scan image
#      uses: ISID/build-and-scan-image@main
#      with:
#        tag: "pegasystems/pega-ready:latest"  # Image name and optionally tag in "name:tag" format
#        hadolint-enable: false
#        path: "."  # Path to base directory to run `docker build` command
#        trivy-enable: false
#        docker-scan-enable: true
#        docker-scan-severity: low
    - name: Scan image
      id: scan
      uses: anchore/scan-action@v2
      with:
        image: "pegasystems/pega-ready:latest"
        fail-build: true;
        severity-cutoff: "medium"
        acs-report-enable: true
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
